export const INITIAL_STATE = 'INITIAL_STATE';

export const HANDLE_INPUT_TOOL = 'HANDLE_INPUT_TOOL';

export const GET_CSV_TOKENIDS = 'GET_CSV_TOKENIDS';
export const REMOVE_CSV_TOKENIDS = 'REMOVE_CSV_TOKENIDS';

export const DECONSTRUCT_CSV = 'DECONSTRUCT_CSV';

export const DECONSTRUCT_TREE = 'DECONSTRUCT_TREE';

export const GET_WL_PROOF = 'GET_WL_PROOF';
export const GET_WL_ROOT = 'GET_WL_ROOT';
